"""
Constants module exports.
"""

from .positions import (
    PositionCategory,
    BARMAN_POSITIONS,
    WAITER_POSITIONS,
    COOK_POSITIONS,
    BARISTA_POSITIONS,
    MANAGEMENT_POSITIONS,
    SUPPORT_POSITIONS,
    ALL_POSITIONS,
    POSITION_CATEGORY_NAMES,
    POSITION_CATEGORIES,
    get_position_category,
    get_all_positions_flat,
    HOOKAH_POSITIONS,
    HOUSEHOLD_POSITIONS,
)

from .cuisines import (
    CUISINES,
    get_cuisine_by_index,
    get_cuisine_index,
)

from .skills import (
    COOK_SKILLS,
    BARMAN_SKILLS,
    WAITER_SKILLS,
    BARISTA_SKILLS,
    MANAGEMENT_SKILLS,
    SUPPORT_SKILLS,
    SKILLS_BY_CATEGORY,
    get_skills_for_position,
    get_all_skills,
)

from .common import (
    UserRole,
    WORK_SCHEDULES,
    EMPLOYMENT_TYPES,
    EXPERIENCE_LEVELS,
    EducationLevel,
    EDUCATION_LEVELS,
    COMPANY_TYPES,
    SalaryType,
    BENEFITS,
    REQUIRED_DOCUMENTS,
    VacancyStatus,
    ResumeStatus,
    ResponseStatus,
    LANGUAGE_LEVELS,
    LANGUAGES,
    LANGUAGES_WITH_FLAGS,
    MAJOR_CITIES,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    # Complaint system
    ComplaintType,
    ComplaintStatus,
    ModerationAction,
    VACANCY_COMPLAINT_REASONS,
    RESUME_COMPLAINT_REASONS,
    COMPLAINT_REASONS,
    IGNORE_DURATIONS,
    COMPLAINTS_FOR_AUTO_MODERATION,
    COMPLAINTS_FOR_AUTO_HIDE,
    DISMISSED_COMPLAINTS_FOR_BAN,
    COMPLAINT_COOLDOWN_MINUTES,
    MAX_COMPLAINTS_PER_DAY,
    PRESET_CITIES,
    INDUSTRY_NAMES,
    INDUSTRIES
)

__all__ = [
    # Positions
    "PositionCategory",
    "BARMAN_POSITIONS",
    "WAITER_POSITIONS",
    "COOK_POSITIONS",
    "BARISTA_POSITIONS",
    "MANAGEMENT_POSITIONS",
    "SUPPORT_POSITIONS",
    "ALL_POSITIONS",
    "POSITION_CATEGORY_NAMES",
    "POSITION_CATEGORIES",
    "get_position_category",
    "get_all_positions_flat",
    # Cuisines
    "CUISINES",
    "get_cuisine_by_index",
    "get_cuisine_index",
    # Skills
    "COOK_SKILLS",
    "BARMAN_SKILLS",
    "WAITER_SKILLS",
    "BARISTA_SKILLS",
    "MANAGEMENT_SKILLS",
    "SUPPORT_SKILLS",
    "SKILLS_BY_CATEGORY",
    "get_skills_for_position",
    "get_all_skills",
    # Common
    "UserRole",
    "WORK_SCHEDULES",
    "EMPLOYMENT_TYPES",
    "EXPERIENCE_LEVELS",
    "EducationLevel",
    "EDUCATION_LEVELS",
    "COMPANY_TYPES",
    "SalaryType",
    "BENEFITS",
    "REQUIRED_DOCUMENTS",
    "VacancyStatus",
    "ResumeStatus",
    "ResponseStatus",
    "LANGUAGE_LEVELS",
    "LANGUAGES",
    "LANGUAGES_WITH_FLAGS",
    "MAJOR_CITIES",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    # Complaint system
    "ComplaintType",
    "ComplaintStatus",
    "ModerationAction",
    "VACANCY_COMPLAINT_REASONS",
    "RESUME_COMPLAINT_REASONS",
    "COMPLAINT_REASONS",
    "IGNORE_DURATIONS",
    "COMPLAINTS_FOR_AUTO_MODERATION",
    "COMPLAINTS_FOR_AUTO_HIDE",
    "DISMISSED_COMPLAINTS_FOR_BAN",
    "COMPLAINT_COOLDOWN_MINUTES",
    "MAX_COMPLAINTS_PER_DAY",
]
